apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-frauca
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-frauca
  template:
    metadata:
      labels:
        app: hazelcast-frauca
    spec:
      containers:
        - name: hazelcast-frauca
          image: frauca/hazelcast-simple-sample
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-frauca
spec:
  type: NodePort
  selector:
    app: hazelcast-frauca
  ports:
  - name: app
    port: 8080
