spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${client-id}
            clientSecret: ${client-secret}

custom:
  password1: "I'm user 1"
  password2: "I'm user 2"