spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${client-id}
            clientSecret: ${client-secret}

custom:
  user1: "I'm user 1"
  user2: "I'm user 2"