version: '2'
services:
    hellofrauca-app:
        image: hellofrauca
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hellofrauca-mysql:3306/hellofrauca?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hellofrauca-mysql:
        extends:
            file: mysql.yml
            service: hellofrauca-mysql
